// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigesTI.Web.Data;

#nullable disable

namespace SigesTI.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611042746_CreacionTablasDefinitivas")]
    partial class CreacionTablasDefinitivas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SigesTI.Web.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsResponsable")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personal", (string)null);
                });

            modelBuilder.Entity("SigesTI.Web.Models.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("AutorizaAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionProblema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EjecutivoAsignado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPersonal")
                        .HasColumnType("int");

                    b.Property<string>("Impresora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtrosSistemas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuestoSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReqSistemas")
                        .HasColumnType("bit");

                    b.Property<string>("ResponsableArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SistemasDetalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadesRed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdPersonal");

                    b.ToTable("Solicitudes", (string)null);
                });

            modelBuilder.Entity("SigesTI.Web.Models.Solicitud", b =>
                {
                    b.HasOne("SigesTI.Web.Models.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("IdPersonal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });
#pragma warning restore 612, 618
        }
    }
}
